name: ItBurns
version: 0.0.5
description: Burn players that try to break protected blocks.
author: cnaude
main: me.cnaude.plugin.ItBurns.IBMain
permissions:
  'itburns.burn':
    description: Players with this will burn if they try to destroy a protected block.
    default: true
  'itburns.reload':
    description: Allows player to reload the config.
    default: op
commands:
    itburns:
        description: Reload the config.
        usage: /itburns reload